### ISSUE TITLE
API rewrite

### ISSUE THREAD

**Issue by frnsys** [coralproject/atoll#20]
these pipelines are intended for handling aggregate data, so we will exclusively be working with collections; as such, it makes sense to directly support combinators such as `map`. We can can also use this approach to make the two types of branching more explicit (now called `fork` and `split`).

These combinators will wrap around Pipes. When validating the pipeline, we check the wrapped types instead of the types of the pipe itself.

The notation used below is as follows:
- `pipe` = some pipe instance
- `p_in` = the pipe's input type
- `p_out` the pipe's output type
### `map(pipe)`

Applies the pipe to each input.
Expects an input of `[p_in]` and outputs `[p_out]`.
### `flatmap(pipe)`

Applies the pipe to each input.
Expects an input of `[p_in]`, expects that `p_out` is a list, and outputs a flattened list of `[p_out]`, which ends up being the same type `p_out`. E.g. if `p_out` is `[int]`, the wrapped out type is also `[int]`.
### `fork(pipe)`

Duplicates the pipe's output to each of the subsequent pipes. Expects branching pipes to follow. Input and output types are unchanged.
### `split(pipe)`

Zips the pipe's output, sending each resulting iterable to a different subsequent pipe.

Expects that the pipe's output is a tuple.

Expects branching pipes to follow, in a number equal to the length of the pipe's tuple output. The individual output iterables are sent to pipes in sequence.
### Other operations

We can start with those, but maybe some "primitive" operations should be included too, such as:
- `mean`
- `sum`
- `count`
- `min`
- `max`
- `sample`
- `distinct`

These are part of the [Spark Python API](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#module-pyspark.sql) so it makes for a easy mapping to that. However, we don't want to maintain a one-to-one mapping in this way.

These could be presented as stock pipes, so you can compose pipelines out of them, then nest them inside other pipelines.

Other operations worth supporting include:
- `groupby`
- `filter`
- `reduce`

But it's unclear how they should be included. Should they just be pipes? Is it necessary to make them explicit?
### API

How do these changes affect how pipelines are composed?

There are a few options (the following examples are equivalent):

```
import atoll as a
Pipeline([PipeA, a.map(PipeB), PipeC, a.fork(PipeD), (PipeE, PipeF, PipeG)])
```

or

```
p = Pipeline()
p.to(PipeA).map(PipeB).to(PipeC).fork(PipeE, PipeF, PipeG)
```

The `to`, `map`, `fork`, in this case could be called "connectors".

I think I prefer the latter, but it will take a bit of playing around to see which feels best.
#### Config syntax

The config syntax will have to change a bit. By default, pipes are assumed to be connected with `to`, but you can override that as well:

``` yaml
MyPipelineName:
    endpoint: /my_pipeline_endpoint
    pipeline:
        - some_module.PipeA: # with kwargs
            arg1: foo
            arg2: 10
        - map: PipeE
        - fork: # branching
            - PipeC
            - PipeD
AnotherPipeline:
    endpoint: /another_pipeline
    pipeline:
        - PipeE
        - MyPipelineName # nested pipelines
```

One tricky part is if you want to pass in keyword arguments to a pipe in which the connector is specified. This could be accomplished like so:

``` yaml
- map:
    pipe: PipeE
    kwarg1: value
```
