### ISSUE TITLE
new config syntax

### ISSUE THREAD

**Issue by frnsys** [coralproject/atoll#23]
The config syntax will have to change a bit. By default, pipes are assumed to be connected with `to`, but you can override that as well:

``` yaml
MyPipelineName:
    endpoint: /my_pipeline_endpoint
    pipeline:
        - some_module.PipeA: # with kwargs
            arg1: foo
            arg2: 10
        - map: PipeE
        - fork: # branching
            - PipeC
            - PipeD
AnotherPipeline:
    endpoint: /another_pipeline
    pipeline:
        - PipeE
        - MyPipelineName # nested pipelines
```

One tricky part is if you want to pass in keyword arguments to a pipe in which the connector is specified. This could be accomplished like so:

``` yaml
- map:
    pipe: PipeE
    kwarg1: value
```
